version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alberto
      POSTGRES_PASSWORD: oing1234
      POSTGRES_DB: macroledsql
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: app-fichaje-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: alberto
      DB_PASSWORD: oing1234
      DB_NAME: macroledsql
    volumes:
      - .:/app
    restart: always

volumes:
  postgres-data:
